### ISSUE TITLE
Wired color

### ISSUE THREAD

**Issue by PIndividual** [TheZoraiz/ascii-image-converter#11] opened 2021-09-10 00:16 UTC
When using the command "-C", image coloring looks wired.
<img width="1600" alt="Screen Shot 2021-09-10 at 8 14 53 AM" src="https://user-images.githubusercontent.com/62368342/132778709-d2ed1328-194e-4fcb-8995-65bbdd216a68.png">

**Comment by PIndividual** [comment] 2021-09-10 00:16
note that this is the original photo
![47f71d4 (1)](https://user-images.githubusercontent.com/62368342/132778756-d639a0a3-93f1-4831-b976-fe5a691c1f94.jpg)

**Comment by TheZoraiz** [comment] 2021-09-10 03:26
From the file path in the terminal screenshot, I'm assuming you're using macOS. This is a common issue for terminals that don't support true colors. Try using [`iTerm2`](https://iterm2.com).

This also looks like a duplicate of issue #9. Perhaps I should include a message in the README or CLI help text.

**Comment by TheZoraiz** [comment] 2021-09-10 22:00
8-bit coloring support has been added as of v1.10.0 (if 24-bit colors aren't supported by terminal) so you should be able to see colored ascii/braille art in your usual terminal from now on. Let me know if it works on your end.

**Comment by PIndividual** [comment] 2021-09-13 00:12
![cube-ascii-art](https://user-images.githubusercontent.com/62368342/133007386-625afb37-e218-4f02-91a7-1ab80b22bb6c.png)

**Comment by PIndividual** [comment] 2021-09-13 00:12
saving image works fine, but still looks wired if I run it in terminal

**Comment by PIndividual** [comment] 2021-09-13 00:13
![Screen Shot 2021-09-13 at 8 13 02 AM](https://user-images.githubusercontent.com/62368342/133007429-af2aa71a-6eac-4c41-a38f-9029fcaa65c2.png)

**Comment by PIndividual** [comment] 2021-09-13 00:14
does it mean that only an 8-bit image could be processed correctly in terminal?

**Comment by TheZoraiz** [comment] 2021-09-13 07:26
That is strange. I tested it myself in the standard macOS terminal and it was working. Can you confirm that you're using v1.10.0 by executing `ascii-image-converter -h`? And what happens if you try coloring with a different terminal like [`iTerm2`](https://iterm2.com)?

**Comment by PIndividual** [comment] 2021-09-13 10:48
Sorry, turns out that I failed to update ascii-image-converter from brew last time, now it works fine for me too, thanks for the help XD
<img width="648" alt="Screen Shot 2021-09-13 at 6 48 11 PM" src="https://user-images.githubusercontent.com/62368342/133070867-3a03b6a4-0d2b-4fbc-b107-fc8f60e73895.png">

**Comment by TheZoraiz** [comment] 2021-09-13 10:53
No worries, glad I could help!

**Closed by TheZoraiz** 2021-09-13 10:53 UTC
Labels: bug
